### PR TITLE
Fix PHP8.1 tentative return types

### PR DESCRIPTION
**Pull request by ChristophWurst**
Similar to https://github.com/bytestream/Mail/pull/2.

@bytestream please have a look :v: 

Upstream PR: https://github.com/horde/Imap_Client/pull/19

### CODE REVIEW

**Comment by ChristophWurst** [comment]
The CI output is … verbose.

**Comment by bytestream** [comment]
Haha, I was just writing the same :sweat_smile: 

Thanks for this :heart: Looks good to me.

**Review by bytestream — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Found a few more within this repo.

**Comment by ChristophWurst** [comment]
This is ready for merge :)

**Pull request merged**
